### ISSUE TITLE
When used with Webpack targeting ES5, builds fail

### ISSUE THREAD

**Issue by chrisjpatty** [mightyiam/get-own-enumerable-property-symbols#4]
Would it be possible to precompile this package to ES5 code so that it doesn't break builds using `create-react-app` from Facebook?  When I build I receive this error:

```
static/js/main.0fba5565.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/stringify-object/index.js:6,0]
```
I'm assuming it's because you're using arrow functions in distributed build of this package right?

**Comment by mightyiam** [comment]
You mean to ES modules format?

**Comment by chrisjpatty** [comment]
Sorry, I just mean to browser-compatible ES5 code. That is unless you're targeting Node exclusively with this package. I just try to avoid having to Babel compile any of my node_modules as part of my webpack build.

**Comment by mightyiam** [comment]
How about you make a pull request and we'll talk about that?

**Comment by chrisjpatty** [comment]
Sure thing! I'm a little new to contributing on Github, so it might take me a minute to figure that out haha, but I'll do my best!
